MY_OS_FULL = "CentOS7.2_All_x64"
MY_PACKAGE_NAME = ""

def version() {
    return sh(script: 'git rev-parse --short HEAD', returnStdout: true)[0 .. 6]
}

def updateCode() {
        stage 'update ShareWebNew'
        dir("/var/JFR/deps_code/$Branch/ShareWebNew") {
            sh "cd /var/JFR/deps_code/$Branch/ShareWebNew/ShareWebSDK && git clean -df && git pull"
            stage 'Recent changes'
            echo sh(script: 'git log -3 --pretty=oneline --stat', returnStdout: true)
        }

        dir("/var/JFR/deps_code/$Branch/ShareWebNew") {
            MY_G_VERSION = version()
            MY_PACKAGE_NAME = "${env.JOB_NAME}-$MY_OS_FULL-${new Date().format('yyyyMMdd-HHmmss')}-$MY_G_VERSION@$Branch-${env.BUILD_NUMBER}"
            echo "${MY_PACKAGE_NAME}"
        }

        stage "update cmake"
        dir("/var/JFR/deps_code/$Branch/Cmake") {
            sh "cd /var/JFR/deps_code/$Branch/Cmake && git pull"
        }
}

def dockerBuild() {
    stage 'build package'
    deleteDir()
    withDockerRegistry([url: '192.168.137.90:5000']) {
        withDockerContainer(args: "--privileged -v /var/JFR/deps_code/$Branch:$WORKSPACE/platform:rw -e WORKSPACE=$WORKSPACE", image: "192.168.137.90:5000/centos7.2:latest") {
            sh "sh $WORKSPACE/platform/ShareWebNew/ShareWebSDK/build.sh"
            sh "cd $WORKSPACE/platform/Cmake/tools; pwd; source $WORKSPACE/platform/Cmake/tools/env.sh \
                && (rm -rf $WORKSPACE/libs_path || true) && mkdir $WORKSPACE/libs_path \
                && cd $WORKSPACE/platform/ShareWebNew/ShareWebSDK \
                && cmake -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_FILE_NAME=${MY_PACKAGE_NAME} -DLIBS_PATH=$WORKSPACE/libs_path \
                && make -j8 package "
        }
    }
}

def uploadPackage() {
    stage 'Upload To FTP'
    sh "ftp -n<<EOF \n\
        open 192.168.122.46 \n\
        user jenkinsftp eisoo.com \n\
        binary \n\
        lcd /var/JFR/deps_code/$Branch/Cmake/packages \n\
        prompt \n\
        mkdir /ci-jobs/package/${env.JOB_NAME} \n\
        put ${MY_PACKAGE_NAME}.tar.gz /ci-jobs/package/${env.JOB_NAME}/${MY_PACKAGE_NAME}.tar.gz \n\
        close \n\
        bye \n\
    EOF"

    sh "rm -f /var/JFR/deps_code/$Branch/Cmake/packages/${MY_PACKAGE_NAME}.tar.gz"
}

node('master') {
    updateCode()
    dockerBuild()
    uploadPackage()
}