# coding=utf-8
'''
配置定位器，通过元素属性定位元素对象
'''
from selenium.webdriver.common.by import By

#登录
username_loc =(By.CLASS_NAME,"_-ShareWebComponents-src-Login-styles-desktop---input-login")
password_loc =(By.CSS_SELECTOR,"[type='password']")
submit_loc =(By.CSS_SELECTOR,"[type='submit']")
login_success_user_loc = (By.CLASS_NAME,"_-ShareWebComponents-src-AccountDropMenu-styles-desktop---username")
login_erro_hint_loc = (By.CLASS_NAME,"_-ShareWebComponents-src-Login-styles-desktop---input-error")

#客户端升级包
windowspac_loc =(By.XPATH,"//div[@class='_-ShareWebComponents-src-ClientsDownload-styles-desktop---container']/div[1]")
macpac_loc =(By.XPATH,"//div[@class='_-ShareWebComponents-src-ClientsDownload-styles-desktop---container']/div[2]")
androidpac_loc =(By.XPATH,"//div[@class='_-ShareWebComponents-src-ClientsDownload-styles-desktop---container']/div[4]")
androidpac_QRCode_loc =(By.XPATH,"//div[@class='_-ShareWebComponents-src-ClientsDownload-styles-desktop---container']/div[4]/div[1]/div[1]/div[1]")

#收藏、内链、外链
#命名规则： 窗口_子窗口_元素_selector
SELECTOR = {
"favorite_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div._-ShareWebComponents-src-Docs-styles-desktop---docs-container > div._-ShareWebComponents-src-Docs-styles-desktop---main > div._-ShareWebComponents-src-Docs-styles-desktop---docs > div > div:nth-child(1) > div._-ShareWebUI-src-Expand-styles-desktop---container._-ShareWebUI-src-Expand-styles-desktop---loaded > div > ul > li > div > div._-ShareWebComponents-src-Docs-List-styles-desktop---wrapper > div:nth-child(3) > div._-ShareWebUI-src-IconGroup-styles-desktop---container > div:nth-child(1) > span",
"doc_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div._-ShareWebComponents-src-Docs-styles-desktop---docs-container > div._-ShareWebComponents-src-Docs-styles-desktop---main > div._-ShareWebComponents-src-Docs-styles-desktop---docs > div > div:nth-child(1) > div._-ShareWebUI-src-Expand-styles-desktop---container._-ShareWebUI-src-Expand-styles-desktop---loaded > div > ul > li > div > div._-ShareWebUI-src-DataList-Item-styles-desktop---checkbox > input",
"internalShare_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div._-ShareWebComponents-src-Docs-styles-desktop---docs-container > div._-ShareWebComponents-src-Docs-styles-desktop---main > div._-ShareWebComponents-src-Docs-styles-desktop---docs > div > div:nth-child(1) > div._-ShareWebUI-src-Expand-styles-desktop---container._-ShareWebUI-src-Expand-styles-desktop---loaded > div > ul > li > div > div._-ShareWebComponents-src-Docs-List-styles-desktop---wrapper > div:nth-child(3) > div._-ShareWebUI-src-IconGroup-styles-desktop---container > div:nth-child(2) > span",
"internalShare_searchBox_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > form > div:nth-child(2) > div:nth-child(2) > div > div > div > div._-ShareWebUI-src-SearchBox-styles-desktop---icon-indent > input",
"internalShare_selectVisitor_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > form > div:nth-child(2) > div:nth-child(2) > div > div > div._-ShareWebUI-src-Locator-styles-desktop---locator > div > div > ul > li > div",
"internalShare_copy_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > form > div:nth-child(1) > div:nth-child(3) > button",
"internalShare_add_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > form > div:nth-child(2) > div:nth-child(3) > button > span",
"internalShare_permissionslist_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div > div > div._-ShareWebUI-src-DataGrid-style-desktop---body-wrap > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > div > div > div > div > a > span > span",
"internalShare_displayIcon_selector":"//l[@l = '\{allow: 1, isowner: false, deny: 0\}']",
"internalShare_addVisitor_searchVisitor_selector":r'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div:nth-child(2) > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom-left > div > div > div._-ShareWebUI-src-Tabs-Main-styles-desktop---main > div > div > div._-ShareWebUI-src-AutoComplete-styles-desktop---container > div > div._-ShareWebUI-src-SearchBox-styles-desktop---icon-indent > input',
"internalShare_addVisitor_selectVisitor_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div:nth-child(2) > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom-left > div > div > div._-ShareWebUI-src-Tabs-Main-styles-desktop---main > div > div > div._-ShareWebUI-src-AutoComplete-styles-desktop---container > div._-ShareWebUI-src-Locator-styles-desktop---locator > div > div > ul > li > div",
"internalShare_addVisitor_ok_selector":r'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div:nth-child(2) > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Footer-styles-desktop---container > div > button:nth-child(1) > span',
"internalShare_addVisitor_tree_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div:nth-child(2) > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom-left > div > div > div._-ShareWebUI-src-Tabs-Main-styles-desktop---main > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---department-tree > div > div > div._-ShareWebUI-src-Tree-Node-styles-desktop---detail > span",
"internalShare_addVisitor_item_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div:nth-child(2) > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom._-ShareWebComponents-src-VisitorAdder-styles-desktop---atom-left > div > div > div._-ShareWebUI-src-Tabs-Main-styles-desktop---main > div > div > div._-ShareWebComponents-src-VisitorAdder-styles-desktop---department-tree > div > div > div._-ShareWebUI-src-Tree-Node-styles-desktop---branch._-ShareWebUI-src-Tree-Node-styles-desktop---expanded > div > div._-ShareWebUI-src-Tree-Node-styles-desktop---detail > a > div > label > span._-ShareWebComponents-src-DepartmentTree-styles-desktop---text._-ShareWebComponents-src-DepartmentTree-styles-desktop---enabled > div > div",
"internalShare_ok_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Footer-styles-desktop---container > div > button:nth-child(1) > span",
"internalShare_delete_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Main-styles-desktop---container > div > div > div > div > div._-ShareWebUI-src-DataGrid-style-desktop---body-wrap > div > table > tbody > tr:nth-child(2) > td:nth-child(5) > div > span",
"internalShare_cancel_selector":r"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div._-ShareWebUI-src-Panel-Footer-styles-desktop---container > div > button:nth-child(2) > span",
"externalShare_selector":r'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div._-ShareWebComponents-src-Docs-styles-desktop---docs-container > div._-ShareWebComponents-src-Docs-styles-desktop---main > div._-ShareWebComponents-src-Docs-styles-desktop---docs > div > div:nth-child(1) > div._-ShareWebUI-src-Expand-styles-desktop---container._-ShareWebUI-src-Expand-styles-desktop---loaded > div > ul > li > div > div._-ShareWebComponents-src-Docs-List-styles-desktop---wrapper > div:nth-child(3) > div._-ShareWebUI-src-IconGroup-styles-desktop---container > div:nth-child(3) > span',
"externalShare_openExternalLink_selector":'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div > div > div._-ShareWebUI-src-FlexBox-Item-styles-desktop---item._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignRight._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignMiddle > button > span',
"externalShare_closeExternalLink_selector":'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div._-ShareWebComponents-src-LinkShare-Configuration-styles-desktop---linkInfo > div > div._-ShareWebUI-src-FlexBox-Item-styles-desktop---item._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignRight._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignMiddle > button > span',
"externalShare_copyLink_selector":'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(1) > div > div._-ShareWebUI-src-FlexBox-Item-styles-desktop---item._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignRight._-ShareWebUI-src-FlexBox-Item-styles-desktop---alignMiddle > div > div > button',
"externalShare_preview_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(1) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div > div:nth-child(1) > div > label > input",
"externalShare_download_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(1) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div > div:nth-child(2) > div > label > input",
"externalShare_upload_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(1) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div > div:nth-child(3) > div > label > input",
"externalShare_expirationDateBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(2) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div > div > a > div",
"externalShare_expirationDateBoxCancel_selector":"body > div._-ShareWebUI-src-PopOver-styles-desktop---layer > div > div > div > div._-ShareWebComponents-src-ValidityBox2-styles-desktop---options",
"externalShare_passwordCheckBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(3) > div._-ShareWebUI-src-Form-Label-styles-desktop---label > label > input",
"externalShare_opensCheckBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(4) > div._-ShareWebUI-src-Form-Label-styles-desktop---label > label > input",
"externalShare_opensInputBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(4) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div",
"externalShare_opensModifyBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > form > div:nth-child(4) > div._-ShareWebUI-src-Form-Field-styles-desktop---field > div > input",
"externalShare_save_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1) > div > div > div:nth-child(1) > button > span",
"externalShare_emailInputBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div._-ShareWebComponents-src-LinkShare-Configuration-styles-desktop---shareOptions > div > div:nth-child(3) > div > div:nth-child(2) > div",
"externalShare_emailModifyBox_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div._-ShareWebComponents-src-LinkShare-Configuration-styles-desktop---shareOptions > div > div:nth-child(3) > div > div:nth-child(2) > div > div > div",
"externalShare_emailSend_selector":"#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div:nth-child(2) > div > div > div > div:nth-child(2) > div._-ShareWebComponents-src-LinkShare-Configuration-styles-desktop---shareOptions > div > div:nth-child(4) > div > div > button > span",
"externalShare_closeButton_selector":'#root > div > div > div.src-views-Root-styles---wrapper > div > div.src-views-Home-styles---main > div > div > div:nth-child(4) > div > div._-ShareWebUI-src-Dialog2-styles-desktop---container > div._-ShareWebUI-src-Dialog2-styles-desktop---header.skin-border-top-color > div > div > span'
}
doc_loc = (By.CSS_SELECTOR, SELECTOR["doc_selector"])
favorite_loc = (By.CSS_SELECTOR, SELECTOR["favorite_selector"])
internalShare_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_selector"])
internalShare_searchBox_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_searchBox_selector"])
internalShare_selectVisitor_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_selectVisitor_selector"])
internalShare_copy_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_copy_selector"])
internalShare_add_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_add_selector"])
internalShare_permissionslist_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_permissionslist_selector"])
internalShare_displayIcon_loc = (By.XPATH, SELECTOR["internalShare_displayIcon_selector"])
internalShare_addVisitor_searchVisitor_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_addVisitor_searchVisitor_selector"])
internalShare_addVisitor_selectVisitor_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_addVisitor_selectVisitor_selector"])
internalShare_addVisitor_ok_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_addVisitor_ok_selector"])
internalShare_addVisitor_tree_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_addVisitor_tree_selector"])
internalShare_addVisitor_item_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_addVisitor_item_selector"])
internalShare_ok_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_ok_selector"])
internalShare_delete_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_delete_selector"])
internalShare_cancel_loc = (By.CSS_SELECTOR, SELECTOR["internalShare_cancel_selector"])
externalShare_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_selector"])
externalShare_openExternalLink_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_openExternalLink_selector"])
externalShare_closeExternalLink_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_closeExternalLink_selector"])
externalShare_copyLink_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_copyLink_selector"])
externalShare_preview_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_preview_selector"])
externalShare_download_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_download_selector"])
externalShare_upload_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_upload_selector"])
externalShare_expirationDateBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_expirationDateBox_selector"])
externalShare_expirationDateBoxCancel_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_expirationDateBoxCancel_selector"])
externalShare_passwordCheckBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_passwordCheckBox_selector"])
externalShare_opensCheckBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_opensCheckBox_selector"])
externalShare_opensInputBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_opensInputBox_selector"])
externalShare_opensModifyBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_opensModifyBox_selector"])
externalShare_save_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_save_selector"])
externalShare_emailInputBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_emailInputBox_selector"])
externalShare_emailModifyBox_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_emailModifyBox_selector"])
externalShare_emailSend_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_emailSend_selector"])
externalShare_closeButton_loc = (By.CSS_SELECTOR, SELECTOR["externalShare_closeButton_selector"])

#--------下载
#鼠标选中
selected_selector_loc = (By.CSS_SELECTOR,"div._-ShareWebUI-src-Fold-styles-desktop---container:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > div:nth-child(1) > input:nth-child(1)")
#1.下载个人文档
download_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(4) > span:nth-child(1)")
#2.下载群组文档
downloadgroup_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(4) > span:nth-child(1)")
#3.下载文件(个人，群组文档中的文件)
downloadfile_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(5) > span:nth-child(1)")
#-------查看大小
#1.查看个人文档大小
viewsizeperson_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(6) > span:nth-child(1)")
#2.查看群组文档大小
viewsizegroup_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(6) > span:nth-child(1)")
#3.查看文件大小
viewsizefile_loc = (By.CSS_SELECTOR,"button._-ShareWebUI-src-Button-styles-desktop---button:nth-child(8)")
#-------复制到
copyto_loc = (By.CSS_SELECTOR,"._-ShareWebComponents-src-Docs-List-styles-desktop---selected > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(5) > span:nth-child(1)")
copyaddress_loc = (By.CSS_SELECTOR,"div._-ShareWebUI-src-Tree-Node-styles-desktop---node:nth-child(2) > div:nth-child(1) > span:nth-child(1)")
select_copyaddress_loc =  (By.CSS_SELECTOR,"div._-ShareWebUI-src-Tree-Node-styles-desktop---node:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > div:nth-child(1)")
surecopy_loc = (By.CSS_SELECTOR,"button._-ShareWebUI-src-Button-styles-desktop---button:nth-child(1)")
